CREATE TABLE IF NOT EXISTS post(
	post_id BIGINT AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	content TEXT,
	upload_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	update_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	views BIGINT DEFAULT 0 NOT NULL,
	PRIMARY KEY(post_id),
	user_id BIGINT NOT NULL,
	FOREIGN KEY(user_id)
	REFERENCES users(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);