CREATE TABLE IF NOT EXISTS comment(
	comment_id BIGINT AUTO_INCREMENT,
	comment TEXT NOT NULL,
	user_id BIGINT NOT NULL,
	post_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	is_deleted BOOLEAN DEFAULT FALSE,
	FOREIGN KEY(post_id)
		REFERENCES post(post_id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(user_id)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	PRIMARY KEY(comment_id)
);