CREATE TABLE IF NOT EXISTS image(
	image_id BIGINT AUTO_INCREMENT,
	path VARCHAR(255) NOT NULL,
	original_name VARCHAR(255) NOT NULL,
	stored_name VARCHAR(255) NOT NULL UNIQUE,
	post_id BIGINT NOT NULL,
	PRIMARY KEY(image_id),
	FOREIGN KEY(post_id)
		REFERENCES post(post_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);